included:
  - Sources
excluded:
  - .build
  - Tools
  - tests
  - cleanup_backup
  - NewFiles

analyzer_rules:
  - unused_declaration
  - unused_import

disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - file_length
  - type_body_length
  - identifier_name
  - empty_count
  - function_parameter_count
  - cyclomatic_complexity
  - multiple_closures_with_trailing_closure
  - trailing_newline

opt_in_rules:
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional

cyclomatic_complexity:
  warning: 15
  error: 25

reporter: "xcode" 